// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedlobbyreferencetobetentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedlobbyreferencetobetentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201703301349452_Added lobby reference to bet entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
