//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Bet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC.Resources.Bet", typeof(Bet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy in.
        /// </summary>
        public static string DisplayBuyIn {
            get {
                return ResourceManager.GetString("DisplayBuyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DisplayDescription {
            get {
                return ResourceManager.GetString("DisplayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge.
        /// </summary>
        public static string DisplayJudge {
            get {
                return ResourceManager.GetString("DisplayJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome 1.
        /// </summary>
        public static string DisplayOutcome1 {
            get {
                return ResourceManager.GetString("DisplayOutcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome 2.
        /// </summary>
        public static string DisplayOutcome2 {
            get {
                return ResourceManager.GetString("DisplayOutcome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string DisplayStartDate {
            get {
                return ResourceManager.GetString("DisplayStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop date.
        /// </summary>
        public static string DisplayStopDate {
            get {
                return ResourceManager.GetString("DisplayStopDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string DisplayTitle {
            get {
                return ResourceManager.GetString("DisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy in is required.
        /// </summary>
        public static string ErrorBuyInRequired {
            get {
                return ResourceManager.GetString("ErrorBuyInRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string ErrorDescriptionRequired {
            get {
                return ResourceManager.GetString("ErrorDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be after start date.
        /// </summary>
        public static string ErrorEndDateBeforeStartDate {
            get {
                return ResourceManager.GetString("ErrorEndDateBeforeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge doesn&apos;t exist.
        /// </summary>
        public static string ErrorJudgeDoesntExist {
            get {
                return ResourceManager.GetString("ErrorJudgeDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a judge.
        /// </summary>
        public static string ErrorJudgeRequired {
            get {
                return ResourceManager.GetString("ErrorJudgeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome is required.
        /// </summary>
        public static string ErrorOutcomeRequired {
            get {
                return ResourceManager.GetString("ErrorOutcomeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an outcome.
        /// </summary>
        public static string ErrorSelectOutcomeRequired {
            get {
                return ResourceManager.GetString("ErrorSelectOutcomeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is required.
        /// </summary>
        public static string ErrorStartDate {
            get {
                return ResourceManager.GetString("ErrorStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop date is required.
        /// </summary>
        public static string ErrorStopDate {
            get {
                return ResourceManager.GetString("ErrorStopDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        public static string ErrorTitleRequired {
            get {
                return ResourceManager.GetString("ErrorTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet is already concluded.
        /// </summary>
        public static string ExceptionBetAlreadyConcluded {
            get {
                return ResourceManager.GetString("ExceptionBetAlreadyConcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome doesn&apos;t exist.
        /// </summary>
        public static string ExceptionOutcomeDoesntExist {
            get {
                return ResourceManager.GetString("ExceptionOutcomeDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user is not judge.
        /// </summary>
        public static string ExceptionUserIsNotJudge {
            get {
                return ResourceManager.GetString("ExceptionUserIsNotJudge", resourceCulture);
            }
        }
    }
}
