//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC.Resources.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string DisplayEmail {
            get {
                return ResourceManager.GetString("DisplayEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string DisplayFirstName {
            get {
                return ResourceManager.GetString("DisplayFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string DisplayLastName {
            get {
                return ResourceManager.GetString("DisplayLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string DisplayPassword1 {
            get {
                return ResourceManager.GetString("DisplayPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string DisplayPassword2 {
            get {
                return ResourceManager.GetString("DisplayPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string DisplayUserName {
            get {
                return ResourceManager.GetString("DisplayUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a smaller number.
        /// </summary>
        public static string ErrorDecimalTooLarge {
            get {
                return ResourceManager.GetString("ErrorDecimalTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit must be a number.
        /// </summary>
        public static string ErrorDepositMustBeNumber {
            get {
                return ResourceManager.GetString("ErrorDepositMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide amount you want to deposit.
        /// </summary>
        public static string ErrorDepositRequired {
            get {
                return ResourceManager.GetString("ErrorDepositRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already in use.
        /// </summary>
        public static string ErrorEmailInUse {
            get {
                return ResourceManager.GetString("ErrorEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email.
        /// </summary>
        public static string ErrorEmailInvalid {
            get {
                return ResourceManager.GetString("ErrorEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your email.
        /// </summary>
        public static string ErrorEmailRequired {
            get {
                return ResourceManager.GetString("ErrorEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your first name.
        /// </summary>
        public static string ErrorFirstNameRequired {
            get {
                return ResourceManager.GetString("ErrorFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid judge.
        /// </summary>
        public static string ErrorJudgeDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorJudgeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your last name.
        /// </summary>
        public static string ErrorLastNameRequired {
            get {
                return ResourceManager.GetString("ErrorLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deposit must be positive.
        /// </summary>
        public static string ErrorNegativeDeposit {
            get {
                return ResourceManager.GetString("ErrorNegativeDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a positive amount to withdraw.
        /// </summary>
        public static string ErrorNegativeWithdraw {
            get {
                return ResourceManager.GetString("ErrorNegativeWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough funds to cover requested withdraw.
        /// </summary>
        public static string ErrorNotEnoughFunds {
            get {
                return ResourceManager.GetString("ErrorNotEnoughFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password.
        /// </summary>
        public static string ErrorPassword1Required {
            get {
                return ResourceManager.GetString("ErrorPassword1Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must repeat the password.
        /// </summary>
        public static string ErrorPassword2Required {
            get {
                return ResourceManager.GetString("ErrorPassword2Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two passwords must be identical.
        /// </summary>
        public static string ErrorPasswordsNotIdentical {
            get {
                return ResourceManager.GetString("ErrorPasswordsNotIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your user name.
        /// </summary>
        public static string ErrorUserNameRequired {
            get {
                return ResourceManager.GetString("ErrorUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name is already in use.
        /// </summary>
        public static string ErrorUserNameTaken {
            get {
                return ResourceManager.GetString("ErrorUserNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username may not contain whitespaces.
        /// </summary>
        public static string ErrorUserNameWhitespace {
            get {
                return ResourceManager.GetString("ErrorUserNameWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw must be a number.
        /// </summary>
        public static string ErrorWithdrawMustBeNumber {
            get {
                return ResourceManager.GetString("ErrorWithdrawMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide amount you want to withdraw.
        /// </summary>
        public static string ErrorWithdrawRequired {
            get {
                return ResourceManager.GetString("ErrorWithdrawRequired", resourceCulture);
            }
        }
    }
}
